version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/eq-stub"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    labels:
      - "patch"
      - "dependencies"