version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/eq-stb"
    target-branch: "main"
    groups:
      pip-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
    schedule:
      interval: "daily"
    labels:
      - "patch"
      - "dependencies"