sudo: required

services:
  - docker

language: bash

before_install:
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y

script:
  - make build_all

branches:
  only:
    - main
