name: Test Image Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-image-builds:
    runs-on: ubuntu-latest

    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      env:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Images
      run: make build-all
